services:
  etl.api:
    image: ${DOCKER_REGISTRY-}etlapi
    build:
      context: .
      dockerfile: Etl.API/Dockerfile
  postgres:
    container_name: etlpostgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: etl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
